openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/products:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  products:
                    -
                      id: 2
                      title: 'Nike Air Force 1 Low Retro'
                      description: 'White/Metallic Gold/Chocolate'
                      currency: PHP
                      price: 7595
                      brand: Nike
                      category: Shoes
                      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/4bcd0306-2bb0-4fcc-b52b-ba7e14b7eab7/air-force-1-low-retro-shoes-j9C2WJ.png'
                      created_at: null
                      updated_at: null
                    -
                      id: 3
                      title: 'Jordan Series Mid'
                      description: 'Pilgrim/White/Sail/Light Olive'
                      currency: PHP
                      price: 5095
                      brand: 'Nike Jordan'
                      category: Shoes
                      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/ff60a6fe-da42-4227-9678-729851ab3fef/jordan-series-mid-shoes-xdNNBc.png'
                      created_at: null
                      updated_at: null
                    -
                      id: 4
                      title: 'Air Jordan 1 Low G'
                      description: Starfish/White/Black
                      currency: PHP
                      price: 8000
                      brand: Jordan
                      category: Shoes
                      image: 'https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/789d8e9f-f93d-4d68-92d1-37e980202cf9/air-jordan-1-low-golf-starfish-dd9315-800-release-date.jpg'
                      created_at: '2022-10-07T17:59:53.000000Z'
                      updated_at: '2022-10-07T17:59:53.000000Z'
                properties:
                  products:
                    type: array
                    example:
                      -
                        id: 2
                        title: 'Nike Air Force 1 Low Retro'
                        description: 'White/Metallic Gold/Chocolate'
                        currency: PHP
                        price: 7595
                        brand: Nike
                        category: Shoes
                        image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/4bcd0306-2bb0-4fcc-b52b-ba7e14b7eab7/air-force-1-low-retro-shoes-j9C2WJ.png'
                        created_at: null
                        updated_at: null
                      -
                        id: 3
                        title: 'Jordan Series Mid'
                        description: 'Pilgrim/White/Sail/Light Olive'
                        currency: PHP
                        price: 5095
                        brand: 'Nike Jordan'
                        category: Shoes
                        image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/ff60a6fe-da42-4227-9678-729851ab3fef/jordan-series-mid-shoes-xdNNBc.png'
                        created_at: null
                        updated_at: null
                      -
                        id: 4
                        title: 'Air Jordan 1 Low G'
                        description: Starfish/White/Black
                        currency: PHP
                        price: 8000
                        brand: Jordan
                        category: Shoes
                        image: 'https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/789d8e9f-f93d-4d68-92d1-37e980202cf9/air-jordan-1-low-golf-starfish-dd9315-800-release-date.jpg'
                        created_at: '2022-10-07T17:59:53.000000Z'
                        updated_at: '2022-10-07T17:59:53.000000Z'
                    items:
                      type: object
      tags:
        - Endpoints
      security: []
  '/api/products/{product_id}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  products:
                    id: 2
                    title: 'Nike Air Force 1 Low Retro'
                    description: 'White/Metallic Gold/Chocolate'
                    currency: PHP
                    price: 7595
                    brand: Nike
                    category: Shoes
                    image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/4bcd0306-2bb0-4fcc-b52b-ba7e14b7eab7/air-force-1-low-retro-shoes-j9C2WJ.png'
                    created_at: null
                    updated_at: null
                properties:
                  products:
                    type: object
                    example:
                      id: 2
                      title: 'Nike Air Force 1 Low Retro'
                      description: 'White/Metallic Gold/Chocolate'
                      currency: PHP
                      price: 7595
                      brand: Nike
                      category: Shoes
                      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/4bcd0306-2bb0-4fcc-b52b-ba7e14b7eab7/air-force-1-low-retro-shoes-j9C2WJ.png'
                      created_at: null
                      updated_at: null
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: et
                description:
                  type: string
                  description: ''
                  example: consequatur
                currency:
                  type: string
                  description: ''
                  example: inventore
                price:
                  type: string
                  description: ''
                  example: et
                brand:
                  type: string
                  description: ''
                  example: ut
                category:
                  type: string
                  description: ''
                  example: deserunt
                image:
                  type: string
                  description: ''
                  example: exercitationem
              required:
                - title
                - description
                - currency
                - price
                - brand
                - category
                - image
      security: []
    delete:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: product_id
        description: 'The ID of the product.'
        example: 2
        required: true
        schema:
          type: integer
  '/api/products/search/{keywords}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  products: []
                properties:
                  products:
                    type: array
                    example: []
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: keywords
        description: ''
        example: qui
        required: true
        schema:
          type: string
  /api/products/category/categories:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  categories:
                    - Shoes
                    - Shoes
                    - Shoes
                properties:
                  categories:
                    type: array
                    example:
                      - Shoes
                      - Shoes
                      - Shoes
                    items:
                      type: string
      tags:
        - Endpoints
      security: []
  '/api/products/category/{category_name}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: category_name
        description: ''
        example: magni
        required: true
        schema:
          type: string
  /api/products/add:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: eum
                description:
                  type: string
                  description: ''
                  example: quod
                currency:
                  type: string
                  description: ''
                  example: aut
                price:
                  type: string
                  description: ''
                  example: architecto
                brand:
                  type: string
                  description: ''
                  example: ea
                category:
                  type: string
                  description: ''
                  example: rerum
                image:
                  type: string
                  description: ''
                  example: reiciendis
              required:
                - title
                - description
                - currency
                - price
                - brand
                - category
                - image
      security: []
tags:
  -
    name: Endpoints
    description: ''
